# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Testes E2E

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Instalar dependências
        run: npm install

      - name: Executar testes com relatório
        run: npm run test:report

      - name: Upload do relatório
        uses: actions/upload-artifact@v3
        with:
          name: mochawesome-report
          path: mochawesome-report


  
